### ISSUE TITLE
sqlite3 versions 3.x.x don't work on node v10

### ISSUE THREAD

**Issue by eeeeeta** [turt2live/matrix-dimension#194]
As above: trying to install matrix-dimension on my server with node 10 didn't work, as the version of sqlite3 that dimension uses is too old for node v10, and doesn't compile.

**Comment by eeeeeta** [comment]
SASS doesn't work either:

```
Module build failed: Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (64)
For more information on which environments are supported please see:                       
https://github.com/sass/node-sass/releases/tag/v4.8.3  
```

**Comment by MTRNord** [comment]
Node 9 works fine (just to mention it)

**Comment by MTRNord** [comment]
Ps: somewhere in their repo is an open issue on what's left to fix on their side to  Support node 10

**Comment by turt2live** [comment]
See also: https://github.com/mapbox/node-sqlite3/issues/973

NodeJS 8 is the supported version of Node for Dimension, although the README previously said "or higher".

I'm going to close this due to it being an upstream issue, and that Node 10 isn't supported by Dimension. Future versions may support Node 10, however for production stuff it's generally recommended to use the LTS.
