### ISSUE TITLE
Docker: UID:GID for volume intransparent

### ISSUE THREAD

**Issue by almereyda** [turt2live/matrix-dimension#224]
It is unmentioned in the documentation that the storage path recursively needs the UID:GID pair `1000:1000` which translates to `node:node`, derived from the `node` base image.

**Comment by ggogel** [comment]
I've never seen a docker image which already fails on setup because it hasn't got permissions to write into the configuration folder. Can't believe this issue exists since over two years.

Replace the path with your dimension config volume path:

`chown -R 1000:1000 /var/lib/docker/volumes/dimension/_data/`
