### ISSUE TITLE
Don't require git repo at runtime

### ISSUE THREAD

**Issue by Bubu** [turt2live/matrix-dimension#357]
Currently dimension requires the git repo to be present at runtime to figure out it's own version.

There's a build step anyway, so how about getting the version at build time and just hardcoding it for the runtime?

That's also one less runtime-dependency then :-).

*Edit:* Turns out this isn't the fatal error I assumed it was, so not that important.

**Comment by lbehm** [comment]
As you already mentioned it's just a log message.

The `CURRENT_VERSION` string is successfully build without the git branch name. So the error isn't helpful because there's no need for an error message. The line can be removed:
https://github.com/turt2live/matrix-dimension/blob/db2298172f8379972567fd298cee1cc1a6e0ae82/src/version.ts#L17
